src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sort;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $preview_image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detail_image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $preview_text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $detail_text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $video;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $viewcounter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $meta_keywords;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;
    
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $createdBy;


    public function getSort(): ?int
    {
        return $this->sort;
    }

    public function setSort(?int $sort): self
    {
        $this->sort = $sort;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPreviewImage(): ?string
    {
        return $this->preview_image;
    }

    public function setPreviewImage(?string $preview_image): self
    {
        $this->preview_image = $preview_image;

        return $this;
    }

    public function getDetailImage(): ?string
    {
        return $this->detail_image;
    }

    public function setDetailImage(?string $detail_image): self
    {
        $this->detail_image = $detail_image;

        return $this;
    }

    public function getPreviewText(): ?string
    {
        return $this->preview_text;
    }

    public function setPreviewText(?string $preview_text): self
    {
        $this->preview_text = $preview_text;

        return $this;
    }

    public function getDetailText(): ?string
    {
        return $this->detail_text;
    }

    public function setDetailText(?string $detail_text): self
    {
        $this->detail_text = $detail_text;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getViewcounter(): ?int
    {
        return $this->viewcounter;
    }

    public function setViewcounter(?int $viewcounter): self
    {
        $this->viewcounter = $viewcounter;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): self
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): self
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getMetaKeywords(): ?string
    {
        return $this->meta_keywords;
    }

    public function setMetaKeywords(?string $meta_keywords): self
    {
        $this->meta_keywords = $meta_keywords;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedBy(): ?int
    {
        return $this->createdBy;
    }

    public function setCreatedBy($createdBy): ?int
    {
        return $this->createdBy = $createdBy;
    }


}

src/Controller/Dashboard/ArticlesController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Blog;
use App\Form\ArticlesType;
use App\Service\FileUploader;
use App\Repository\BlogRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/articles")
 */
class ArticlesController extends BaseController
{
    /**
     * @Route("/", name="dashboard_articles_index", methods={"GET"})
     */
    public function index(BlogRepository $articlesRepository): Response
    {
        return $this->render('dashboard/articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(), 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="dashboard_articles_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $article = new Blog();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //$article->setCreatedBy( $this->getUser()->getId() );

            $previewImage = $request->files->get('articles')['preview_image'];
            $detailImage = $request->files->get('articles')['detail_image'];

            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);                
                $article->setDetailImage($fileName);
                $article->setPreviewImage($fileName);
            }else{
                if($previewImage){
                    $fileName = $fileUploader->upload($previewImage);
                    $article->setPreviewImage($fileName);
                }
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('dashboard_articles_index');
        }

        return $this->render('dashboard/articles/new.html.twig', [
            'item' => $article,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_articles_show", methods={"GET"})
     */
    public function show(Blog $article): Response
    {
        return $this->render('dashboard/articles/show.html.twig', [
            'article' => $article, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dashboard_articles_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Blog $article, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $previewImage = $request->files->get('articles')['preview_image'];
            $detailImage = $request->files->get('articles')['detail_image'];

            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);                
                $article->setDetailImage($fileName);
                $article->setPreviewImage($fileName);
            }else{
                if($previewImage){
                    $fileName = $fileUploader->upload($previewImage);
                    $article->setPreviewImage($fileName);
                }
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dashboard_articles_index', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('dashboard/articles/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="articles_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Blog $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articles_index');
    }
}

src/Controller/Dashboard/BaseController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\User;

use Symfony\Component\Security\Core\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//use Symfony\Component\Security\Core\User\UserInterface\UserInterface;


abstract class BaseController extends AbstractController
{
    public $user;
    private $security;

    public function __construct(Security $security){
        $this->security = $security;
        $this->user = $this->security->getUser();
    }
}

src/Controller/Dashboard/CategoryController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Category;
use App\Form\CategoryType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/category")
 */
class CategoryController extends BaseController
{
    /**
     * @Route("/", name="dashboard_category_index", methods={"GET"})
     */
    public function index(): Response
    {
        $categories = $this->getDoctrine()
            ->getRepository(Category::class)
            ->findAll();

        return $this->render('dashboard/category/index.html.twig', [
            'categories' => $categories, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="category_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($category);
            $entityManager->flush();

            return $this->redirectToRoute('dashboard_category_index');
        }

        return $this->render('dashboard/category/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_category_show", methods={"GET"})
     */
    public function show(Category $category): Response
    {
        return $this->render('dashboard/category/show.html.twig', [
            'category' => $category,
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="category_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Category $category): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dashboard_category_index', [
                'id' => $category->getId(),
            ]);
        }

        return $this->render('dashboard/category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="category_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Category $category): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('category_index');
    }
}

src/Controller/Dashboard/DeliveryController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Delivery;
use App\Form\DeliveryType;
use App\Repository\DeliveryRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/delivery")
 */
class DeliveryController extends BaseController
{
    /**
     * @Route("/", name="dashboard_delivery_index", methods={"GET"})
     */
    public function index(DeliveryRepository $deliveryRepository): Response
    {
        return $this->render('dashboard/delivery/index.html.twig', [
            'deliveries' => $deliveryRepository->findAll(),'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="dashboard_delivery_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $delivery = new Delivery();
        $form = $this->createForm(DeliveryType::class, $delivery);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($delivery);
            $entityManager->flush();

            return $this->redirectToRoute('delivery_index');
        }

        return $this->render('dashboard/delivery/new.html.twig', [
            'delivery' => $delivery,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_delivery_show", methods={"GET"})
     */
    public function show(Delivery $delivery): Response
    {
        return $this->render('dashboard/delivery/show.html.twig', [
            'delivery' => $delivery,'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dashboard_delivery_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Delivery $delivery): Response
    {
        $form = $this->createForm(DeliveryType::class, $delivery);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('delivery_index', [
                'id' => $delivery->getId(),
            ]);
        }

        return $this->render('dashboard/delivery/edit.html.twig', [
            'delivery' => $delivery,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_delivery_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Delivery $delivery): Response
    {
        if ($this->isCsrfTokenValid('delete'.$delivery->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($delivery);
            $entityManager->flush();
        }

        return $this->redirectToRoute('delivery_index');
    }
}

src/Controller/Dashboard/IndexController.php
<?php

namespace App\Controller\Dashboard;

use Symfony\Component\Routing\Annotation\Route;

class IndexController extends BaseController
{
    /**
     * @Route("/dashboard", name="dashboard")
    */

    public function index()
    {

        //rolses ROLE_ADMIN, IS_AUTHENTICATED_FULLY
       // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        //$this->isGranted('IS_AUTHENTICATED_FULLY');
        //dd($this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY'));
        //dd($this->isGranted('IS_AUTHENTICATED_FULLY'));

//        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
//            throw $this->createAccessDeniedException();
//        }

        return $this->render('dashboard/index/index.html.twig',[
            'user'=>$this->user
        ]);

    }

}

templates/dashboard/articles/_delete_form.html.twig
<form method="post" action="{{ path('articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/dashboard/articles/_form.html.twig
{{ form_start(form) }}


<div class="row">
    <div class="col-md-7">
<div class="card">
    <div class="card-body">

            {# <div class="d-none">
            {{ form_label(form.created_by, 'Created by') }}<br>
            {{ form_widget(form.created_by) }}
            </div> #}

            <div class="form-group">     
                {{ form_label(form.sort, 'Sort') }}
                {{ form_widget(form.sort, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">     
                {{ form_label(form.active, 'Active') }}
                {{ form_widget(form.active) }}
            </div>

            <div class="form-group">     
                {{ form_label(form.title, 'Title') }}
                {{ form_widget(form.title, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.preview_text, 'Preview text') }}
                {{ form_widget(form.preview_text, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">  
                {{ form_label(form.detail_text, 'Detail text') }}  
                {{ form_widget(form.detail_text, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">    
                {{ form_label(form.meta_title, 'Meta title') }} 
                {{ form_widget(form.meta_title, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">  
                {{ form_label(form.meta_description, 'Meta description') }}    
                {{ form_widget(form.meta_description, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group"> 
                {{ form_label(form.meta_keywords, 'Meta keywords') }}     
                {{ form_widget(form.meta_keywords, { 'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                <button class="btn btn-success">{{ button_label|default('Save') }}</button>
            </div> 
    </div>
</div>    
    </div>

    <div class="col-md-5">
<div class="card">
    <div class="card-body">

        <div class="form-group">
            {{ form_label(form.preview_image, 'Preview image') }}
            {{ form_widget(form.preview_image) }}
        </div>

        <div class="form-group">
            {# {% if form.preview_image %}
            <div class="form-image">
            <img src="{{form.preview_image}}" alt="{{form.preview_image}}">
            </div>
            {% endif %} #}

            {{ form_label(form.detail_image, 'Detail image') }}
            {{ form_widget(form.detail_image) }}
        </div>

    </div>
</div>
    
    </div>
</div>

{{ form_end(form) }}

templates/dashboard/articles/edit.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Edit Articles{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-title">
            <div class="col-12">
            <h4>Edit Articles</h4>
            <a href="{{ path('dashboard_articles_index') }}">back to list</a>
            </div>
        </div>
    </div>


    {{ include('dashboard/articles/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('dashboard/articles/_delete_form.html.twig') }}
{% endblock %}

templates/dashboard/articles/index.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
<div class="card">

<div class="card-header">
 <h3>Articles</h3>
 <p><a class="btn btn-success" href="{{ path('dashboard_articles_new') }}">Add Article</a></p>
</div>

<div class="card-body">
   <table class="table table-bordered admin-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Active</th>
                <th>Title</th>
                <th>Sort</th>
                <th>Created by</th>
                <th>Created date</th>
                <th>Updated date</th>
                <th>Preview text</th>
                <th>Preview image</th>
                <th>Detail text</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.active }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.sort }}</td>
                <td>{{ article.createdBy }}</td>

                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s')}}</td>
                <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s')}}</td>

                <td>{{ article.previewText }}</td>
                <td>
                    {% if article.previewImage %}
                        <a target="_blank" href="{{ article.previewImage }}"><img src="{{ article.previewImage }}"></a>
                    {% endif %}
                </td>
                <td>{{ article.detailText }}</td>
                <td>
                    <a href="{{ path('dashboard_articles_show', {'id': article.id}) }}">Show</a>
                    <a href="{{ path('dashboard_articles_edit', {'id': article.id}) }}">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</div>
 
{% endblock %}

templates/dashboard/articles/new.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}New Articles{% endblock %}

{% block body %}
    <h4>Add Articles</h4>

    {{ include('dashboard/articles/_form.html.twig') }}

    <a href="{{ path('dashboard_articles_index') }}">back to list</a>
{% endblock %}

templates/dashboard/articles/show.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <h3>Articles</h3>

    <table class="table table-bordered admin-table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ article.active }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Sort</th>
                <td>{{ article.sort }}</td>
            </tr>
            <tr>
                <th>Created_by</th>
                <td>{{ article.createdBy }}</td>
            </tr>
            {% if article.previewImage %}
                <tr>
                    <th>Изображения анонса</th>
                    <td><a target="_blank"  href="{{ article.previewImage }}"><img class="img-responsive" src="{{ article.previewImage }}" alt="{{ article.title }}"></a></td>
                </tr>
            {% endif %}

            {% if article.detailImage %}
                <tr>
                    <th>Детальная картинка</th>
                    <td><a target="_blank"  href="{{ article.detailImage }}"><img class="img-responsive" src="{{article.detailImage }}" alt="{{ article.title }}"></a></td>
                </tr>
            {% endif %}
            <tr>
                <th>Preview_text</th>
                <td>{{ article.previewText }}</td>
            </tr>
            <tr>
                <th>Detail_text</th>
                <td>{{ article.detailText }}</td>
            </tr>
            <tr>
                <th>Meta_title</th>
                <td>{{ article.metaTitle }}</td>
            </tr>
            <tr>
                <th>Meta_description</th>
                <td>{{ article.metaDescription }}</td>
            </tr>
            <tr>
                <th>Meta_keywords</th>
                <td>{{ article.metaKeywords }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('dashboard_articles_edit', {'id': article.id}) }}">edit</a>

    <a href="{{ path('dashboard_articles_index') }}">back to list</a>

    {{ include('dashboard/articles/_delete_form.html.twig') }}
{% endblock %}