src/Entity/Coupon.php
<?php

namespace App\Entity;

use App\Repository\CouponRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CouponRepository::class)
 */
class Coupon
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $expire_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(?int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getExpireDate(): ?\DateTimeInterface
    {
        return $this->expire_date;
    }

    public function setExpireDate(?\DateTimeInterface $expire_date): self
    {
        $this->expire_date = $expire_date;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/Dashboard/ArticlesController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Blog;
use App\Form\ArticlesType;
use App\Service\FileUploader;
use App\Repository\BlogRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/articles")
 */
class ArticlesController extends BaseController
{
    /**
     * @Route("/", name="dashboard_articles_index", methods={"GET"})
     */
    public function index(BlogRepository $articlesRepository): Response
    {
        return $this->render('dashboard/articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(), 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="dashboard_articles_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $article = new Blog();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //$article->setCreatedBy( $this->getUser()->getId() );

            $previewImage = $request->files->get('articles')['preview_image'];
            $detailImage = $request->files->get('articles')['detail_image'];

            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);                
                $article->setDetailImage($fileName);
                $article->setPreviewImage($fileName);
            }else{
                if($previewImage){
                    $fileName = $fileUploader->upload($previewImage);
                    $article->setPreviewImage($fileName);
                }
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('dashboard_articles_index');
        }

        return $this->render('dashboard/articles/new.html.twig', [
            'item' => $article,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_articles_show", methods={"GET"})
     */
    public function show(Blog $article): Response
    {
        return $this->render('dashboard/articles/show.html.twig', [
            'article' => $article, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dashboard_articles_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Blog $article, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $previewImage = $request->files->get('articles')['preview_image'];
            $detailImage = $request->files->get('articles')['detail_image'];

            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);                
                $article->setDetailImage($fileName);
                $article->setPreviewImage($fileName);
            }else{
                if($previewImage){
                    $fileName = $fileUploader->upload($previewImage);
                    $article->setPreviewImage($fileName);
                }
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dashboard_articles_index', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('dashboard/articles/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="articles_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Blog $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articles_index');
    }
}

src/Controller/Dashboard/BaseController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\User;

use Symfony\Component\Security\Core\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//use Symfony\Component\Security\Core\User\UserInterface\UserInterface;


abstract class BaseController extends AbstractController
{
    public $user;
    private $security;

    public function __construct(Security $security){
        $this->security = $security;
        $this->user = $this->security->getUser();
    }
}

src/Controller/Dashboard/CategoryController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Category;
use App\Form\CategoryType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/category")
 */
class CategoryController extends BaseController
{
    /**
     * @Route("/", name="dashboard_category_index", methods={"GET"})
     */
    public function index(): Response
    {
        $categories = $this->getDoctrine()
            ->getRepository(Category::class)
            ->findAll();

        return $this->render('dashboard/category/index.html.twig', [
            'categories' => $categories, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="category_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($category);
            $entityManager->flush();

            return $this->redirectToRoute('dashboard_category_index');
        }

        return $this->render('dashboard/category/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_category_show", methods={"GET"})
     */
    public function show(Category $category): Response
    {
        return $this->render('dashboard/category/show.html.twig', [
            'category' => $category,
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="category_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Category $category): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dashboard_category_index', [
                'id' => $category->getId(),
            ]);
        }

        return $this->render('dashboard/category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="category_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Category $category): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('category_index');
    }
}

src/Controller/Dashboard/CertificatesController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Certificates;
use App\Form\CertificatesType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FileUploader;

/**
 * @Route("/dashboard/certificates")
 */
class CertificatesController extends BaseController
{
    /**
     * @Route("/", name="dashboard_certificates_index", methods={"GET"})
     */
    public function index(): Response
    {
        $certificates = $this->getDoctrine()
            ->getRepository(Certificates::class)
            ->findAll();

        return $this->render('dashboard/certificates/index.html.twig', [
            'certificates' => $certificates, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/new", name="certificates_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $certificate = new Certificates();
        $form = $this->createForm(CertificatesType::class, $certificate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $certificate->setCreatedBy( $this->getUser()->getId() );
            
            $previewImage = $request->files->get('certificates')['previewImage'];
            if($previewImage){
                $fileName = $fileUploader->upload($previewImage);
                $certificate->setPreviewImage($fileName); 
            }

            $detailImage = $request->files->get('certificates')['detailImage'];
            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);
                $certificate->setDetailImage($fileName); 
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($certificate);
            $entityManager->flush();

            return $this->redirectToRoute('dashboard_certificates_index');
        }

        return $this->render('dashboard/certificates/new.html.twig', [
            'certificate' => $certificate,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="dashboard_certificates_show", methods={"GET"})
     */
    public function show(Certificates $certificate): Response
    {
        return $this->render('dashboard/certificates/show.html.twig', [
            'certificate' => $certificate, 'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="certificates_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Certificates $certificate, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(CertificatesType::class, $certificate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $certificate->setCreatedBy( $this->getUser()->getId() );
            
            $previewImage = $request->files->get('certificates')['previewImage'];
            if($previewImage){
                $fileName = $fileUploader->upload($previewImage);
                $certificate->setPreviewImage($fileName); 
            }

            $detailImage = $request->files->get('certificates')['detailImage'];
            if($detailImage){
                $fileName = $fileUploader->upload($detailImage);
                $certificate->setDetailImage($fileName); 
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dashboard_certificates_index', [
                'id' => $certificate->getId(),
            ]);
        }

        return $this->render('dashboard/certificates/edit.html.twig', [
            'certificate' => $certificate,
            'form' => $form->createView(),
            'user'=>$this->user
        ]);
    }

    /**
     * @Route("/{id}", name="certificates_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Certificates $certificate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$certificate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($certificate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('dashboard_certificates_index');
    }
}

src/Controller/Dashboard/IndexController.php
<?php

namespace App\Controller\Dashboard;

use Symfony\Component\Routing\Annotation\Route;

class IndexController extends BaseController
{
    /**
     * @Route("/dashboard", name="dashboard")
    */

    public function index()
    {

        //rolses ROLE_ADMIN, IS_AUTHENTICATED_FULLY
       // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        //$this->isGranted('IS_AUTHENTICATED_FULLY');
        //dd($this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY'));
        //dd($this->isGranted('IS_AUTHENTICATED_FULLY'));

//        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
//            throw $this->createAccessDeniedException();
//        }

        return $this->render('dashboard/index/index.html.twig',[
            'user'=>$this->user
        ]);

    }

}

templates/dashboard/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/dashboard/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/dashboard/user/edit.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h3>Edit User</h3>

    <p><a href="{{ path('user_index') }}">back to list</a></p>

    {{ include('dashboard/user/_form.html.twig', {'button_label': 'Update'}) }}
<br>
    {{ include('dashboard/user/_delete_form.html.twig') }}
{% endblock %}

templates/dashboard/user/index.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
<div class="card">
<div class="card-header">
    <h3>Users</h3>
    <p><a class="btn btn-success" href="{{ path('user_new') }}">Add new user</a> </p>   
</div>

<div class="card-body">

<div class="table-responsive">
    <table class="table table-bordered admin-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Created_date</th>
                <th>Updated_date</th>
                <th>Active</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.createdDate ? user.createdDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updatedDate ? user.updatedDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.active }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

</div>
{% endblock %}

templates/dashboard/user/new.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h3>Create new User</h3>

    <p><a href="{{ path('user_index') }}">back to list</a></p>

    {{ include('dashboard/user/_form.html.twig') }}

{% endblock %}

templates/dashboard/user/show.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h3>User</h3>

    <p><a href="{{ path('user_index') }}">back to list</a></p>

    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>Created_date</th>
                <td>{{ user.createdDate ? user.createdDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_date</th>
                <td>{{ user.updatedDate ? user.updatedDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ user.active }}</td>
            </tr>
        </tbody>
    </table>

    <p><a class="btn btn-success" href="{{ path('user_edit', {'id': user.id}) }}">edit</a></p>

    {{ include('dashboard/user/_delete_form.html.twig') }}
{% endblock %}